### ISSUE TITLE
关于软件的一点疑惑

### ISSUE THREAD

**Issue by WerewolfII** [peterzhang1234/SHU-Map#1]
学长您好，我是上海大学的一名大三学生。今年的课程项目也是校园最短路径规划，参考了您的方案，感觉您的方案非常出色，但不知使用什么编译器编译运行这些文件。希望得到您的回复。

**Comment by peterzhang1234** [comment]
> 学长您好，我是上海大学的一名大三学生。今年的课程项目也是校园最短路径规划，参考了您的方案，感觉您的方案非常出色，但不知使用什么编译器编译运行这些文件。希望得到您的回复。
 

O(∩_∩)O哈哈~，感谢你的认可，我用的是Qt这个应用开发框架，用的C++，在Windows环境你可以用Qt Creator进行开发编译，在Linux环境下直接使用qmake和make就可以了。如果你熟悉python，也可以使用PyQt。
我这个方案只体现了算法，而且直接在图上找坐标点是很笨的方法，你可以使用高德或者百度的API，他们的地图更加精准，实用性大大提高；还有，你可以在新建一个小窗口进行一个导航预览，放大导航细节。

**Comment by WerewolfII** [comment]
谢谢学姐/学长的解答，也谢谢您的建议。在您的方案和其他同样优秀的方案的帮助下，我们会争取出色地完成本次课程项目，再次感谢您的解答。祝您在学业/工作中一帆风顺，事业有成。
